version: "3.8"
services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=new_db
      - MYSQL_USER=mysql_user
      - MYSQL_PASSWORD=mysql_password
      - MYSQL_ROOT_PASSWORD=mysql_password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - mysql_network
volumes:
  db-data: ~
networks:
  mysql_network:
    name: mysql-container_mysql_network
    driver: bridge
